### ISSUE TITLE
Spring Rest Docs를 이용하여 Roadmap API 문서 작성하기

### ISSUE THREAD

**Issue by onezerokang** [onezerokang/road-maker-kotlin#4]
## Todo

- [ ] 로드맵 다수 조회(페이징)
- [ ] 로드맵 단일 조회
- [ ] 로드맵 생성
- [ ] 로드맵 썸네일 등록
